---
- name: asdf present [MacOS]
  community.general.homebrew:
    name: asdf
    state: present
  when: ansible_distribution == 'MacOSX'

- name: asdf present [Linux]
  ansible.builtin.package:
    name: asdf
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
