---
- name: Define DOTFILES_PATH env var
  lineinfile:
    path: "${HOME}/.bashrc"
    line: "export DOTFILES_PATH={{ dotfiles_path }}"

- name: Source bashrc custom file
  lineinfile:
    path: "${HOME}/.bashrc"
    line: ". ${DOTFILES_PATH}/config/source_this.bash"

- name: bash-git-prompt init
  ansible.builtin.command: git submodule init
  args:
    chdir: "{{ dotfiles_path }}"

- name: bash-git-prompt update
  ansible.builtin.command: git submodule update
  args:
    chdir: "{{ dotfiles_path }}"
