---
- name: mise present [MacOS]
  community.general.homebrew:
    name: mise
    state: present
  when: ansible_os_family == 'Darwin'

- name: install mise [Linux]
  ansible.builtin.shell: |
    curl https://mise.run | sh
  when: ansible_os_family == 'Debian'

- name: install configured default tools with mise
  ansible.builtin.shell: mise install
