---
- name: Download and add the GitHub CLI GPG key
  become: true
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
    mode: "go+r"

- name: Add the GitHub CLI repository
  become: true
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/github-cli.list
    line: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    create: yes

- name: Update package cache [Linux]
  become: true
  tags: always
  apt:
    update_cache: true
  changed_when: false
  ignore_errors: yes

- name: Packages present [Linux]
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    # - dive # only available as .deb file
    # - git-delta # only available as .deb file
    #
    # - asciidoctor installs ruby 3.1
    - curl
    - fd-find
    - fonts-powerline
    - fonts-roboto
    - gh
    - git
    - htop
    - httpie
    - mosh
    - mycli
    - pgcli
    - python3-pip # for nvim
    - silversearcher-ag
    - tar
    - tmux
    - unzip
    - watch
    - yamllint

# vim-nox installs ruby 3.1, that is a problem in CDE's
- name: Vim present [Linux]
  become: true
  ansible.builtin.package:
    name: vim-nox
    state: present
  when: install_nvim != true
