---
- name: Update package cache [MacOS]
  tags: always
  ansible.builtin.command: brew update
  changed_when: false

- name: packages present [MacOS]
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - 7zip
    - asciidoctor
    - bpytop
    - dive
    - docutils
    - eza
    - fd
    - fzf
    - git
    - git-delta
    - gnu-tar
    - htop
    - httpie
    - k9s
    - kubectx
    - macvim
    - mosh
    - mycli
    - pgcli
    - prettier
    - rg
    - the_silver_searcher
    - watch
    - yamllint
    - yazi

- name: install casks [MacOs]
  ansible.builtin.command: brew install --cask "{{ item }}"
  loop:
    - font-roboto-mono-nerd-font
    - font-roboto-mono-for-powerline
