---
- name: Packages are present [Linux]
  import_tasks: packages_present_linux.yml
  when: ansible_os_family == 'Debian'

- name: Packages are present [MacOSX]
  import_tasks: packages_present_macos.yml
  when: ansible_os_family == 'Darwin'

- name: nvim present
  import_tasks: nvim_present.yml

- name: Lazydocker present
  import_tasks: lazydocker_present.yml

