---
- name: Link dotfiles
  import_tasks: link_dotfiles.yml

- name: Link programs config
  import_tasks: link_programs_configs.yml

- name: Configure zsh
  import_tasks: zsh_setup.yml
  when: ansible_facts['user_shell'] == '/bin/zsh'

- name: Configure bash
  import_tasks: bash_setup.yml
  when: ansible_facts['user_shell'] == '/bin/bash'

- name: Setup vim
  import_tasks: vim_setup.yml
  when: install_nvim != true
