---
- name: Dotfiles setup for cloud development environment

  hosts: all

  vars:
    dotfiles_path: "{{ playbook_dir }}/.."
    install_asdf: false
    install_nvim: true

  tasks:
    - name: Packages are present
      import_tasks: packages_present.yml

    - name: Terminal Setup
      import_tasks: terminal_setup.yml
