---
- name: Dotfiles setup for gitpod
  vars:
    ansible_python_interpreter: /home/gitpod/.pyenv/shims/python

  hosts: all
  tasks:
    - name: Packages are present
      import_tasks: packages_present.yml

    - name: Terminal Setup
      import_tasks: terminal_setup.yml
