---
- name: Link dotfiles
  ansible.builtin.file:
    src: "${HOME}/.dotfiles/{{ item }}"
    dest: "${HOME}/{{ item }}"
    state: link
  loop:
    - .UltiSnips
    - .editrc
    - .gemrc
    - .gitignore_global
    - .inputrc
    - .vimrc
