---
- name: Ensure $HOME/.config exists
  ansible.builtin.file:
    path: "$HOME/.config"
    state: directory
    mode: 0755

- name: Link programs config
  ansible.builtin.file:
    src: "{{ dotfiles_path }}/config/{{ item }}"
    dest: "${HOME}/.config/{{ item }}"
    state: link
  loop:
    - alacritty
    - i3
    - nvim
    - yamllint
