---
- name: Dotfiles setup
  hosts: all

  vars:
    dotfiles_path: "{{ playbook_dir }}/.."
    install_asdf: true
    install_nvim: true

  tasks:
    - name: Packages are present
      import_tasks: playbooks/packages_present.yml

    - name: Terminal Setup
      import_tasks: playbooks/terminal_setup.yml

    - name: asdf present
      import_tasks: playbooks/asdf_present.yml
      when: install_asdf == true
