---
- name: Install nvim python dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip"

- name: Clone packer
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "${HOME}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    recursive: true
    force: true
    depth: 1

- name: Install pyneovim package
  ansible.builtin.command: pip3 install neovim

- name: Install nvim plugins using Packer
  ansible.builtin.command: $HOME/bin/nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
