---
- name: Packages are present [Linux]
  import_tasks: packages_present_linux.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Packages are present [MacOSX]
  import_tasks: packages_present_macos.yml
  when: ansible_distribution == 'MacOSX'

- name: Install lazydocker [Linux/OSX/Windows]
  ansible.builtin.command: curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
