---
- name: Update Package Cache [Linux]
  become: true
  tags: always
  apt:
    update_cache: true
  changed_when: false
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Update Package Cache [Linux]
  tags: always
  ansible.builtin.command: brew update
  changed_when: false
  when: ansible_distribution == 'MacOSX'

- name: packages present [Linux]
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - fonts-powerline
    - git
    - htop
    - httpie
    - mosh
    - rbenv
    - silversearcher-ag
    - vim-nox
    - watch
    - yamllint
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: packages present [macos]
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - docutils
    - exa
    - fzf
    - git
    - htop
    - bpytop
    - httpie
    - macvim
    - mosh
    - rbenv
    - the_silver_searcher
    - watch
    - kubectx
    - k9s
    - yamllint
  when: ansible_distribution == 'MacOSX'
