---
- name: Update package cache [MacOS]
  tags: always
  ansible.builtin.command: brew update
  changed_when: false

- name: packages present [MacOS]
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - asciidoctor
    - bpytop
    - dive
    - docutils
    - exa
    - fzf
    - git
    - git-delta
    - htop
    - httpie
    - k9s
    - kubectx
    - macvim
    - mosh
    - pgcli
    - prettier
    - rbenv
    - the_silver_searcher
    - watch
    - yamllint

- name: Ensure $HOME/bin exists
  ansible.builtin.file:
    path: "${HOME}/bin"
    state: directory

- name: Download nvim tarfile
  get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
    dest: "/tmp/nvim-macos.tar.gz"

- name: Extract nvim tarfile
  ansible.builtin.unarchive:
    src: "/tmp/nvim-macos.tar.gz"
    dest: "${HOME}/bin"

- name: Link binary
  ansible.builtin.file:
    src: "${HOME}/bin/nvim-macos/bin/nvim"
    dest: "${HOME}/bin/nvim"
    state: link
