---
- name: Update package cache [MacOS]
  tags: always
  ansible.builtin.command: brew update
  changed_when: false

- name: packages present [MacOS]
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - asciidoctor
    - bpytop
    - dive
    - docutils
    - exa
    - fzf
    - git
    - git-delta
    - htop
    - httpie
    - k9s
    - kubectx
    - macvim
    - mosh
    - pgcli
    - prettier
    - the_silver_searcher
    - watch
    - yamllint
    - fd
    - rg

- name: Ensure $HOME/bin exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory

- name: Download nvim tarfile
  get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
    dest: "/tmp/nvim-macos.tar.gz"

- name: Extract nvim tarfile
  command:
    cmd: tar -xzf /tmp/nvim-macos.tar.gz -C "{{ ansible_env.HOME }}/bin"

- name: Link binary
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/bin/nvim-macos/bin/nvim"
    dest: "{{ ansible_env.HOME }}/bin/nvim"
    state: link
