---
- name: Creates VIM directory
  file:
    path: "${HOME}/.vim/autoload"
    state: directory

- name: Install Plug for VIM
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "${HOME}/.vim/autoload/plug.vim"

- name: Install vim plugins using Plug
  ansible.builtin.command: vim +PlugInstall +qall
