---
name: Ansible Linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-ansible-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install test dependencies.
        run: |
          sudo apt-get install -y --no-install-recommends python3-setuptools python3-pip python3-wheel
          sudo pip3 install ansible

      - name: Set up the test environment.
        run: ansible-galaxy install -r requirements.yml
        working-directory: setup

      - name: Test the playbook's syntax.
        run: ansible-playbook main.yml --syntax-check
        working-directory: setup

      - name: Test the playbook.
        run: ansible-playbook main.yml -i inventory
        env:
          ANSIBLE_FORCE_COLOR: '1'
        working-directory: setup

      - name: Check home
        run: |
          ls -la $HOME
          ls -la $HOME/.config

  integration-ansible-gitpod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install test dependencies.
        run: |
          sudo apt-get install -y --no-install-recommends python3-setuptools python3-pip python3-wheel
          sudo pip3 install ansible

      - name: Test the playbook's syntax.
        run: ansible-playbook gitpod.yml --syntax-check
        working-directory: setup

      - name: Test the playbook.
        run: ansible-playbook gitpod.yml -i inventory
        env:
          ANSIBLE_FORCE_COLOR: '1'
        working-directory: setup

      - name: Check home
        run: |
          ls -la $HOME
          ls -la $HOME/.config
