---
name: Ansible

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-ansible:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-latest]
        shell: [bash, zsh]
        exclude:
          - os: macos-latest
            shell: bash # Exclude bash for macOS

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: "[macos] Install brew"
        if: matrix.os == 'macos-latest'
        uses: Homebrew/actions/setup-homebrew@master

      - name: "[macos] Install ansible"
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew upgrade
          brew install ansible

      - name: "[linux] Install test dependencies"
        if: matrix.os != 'macos-latest'
        run: |
          sudo apt-get install -y --no-install-recommends python3-setuptools python3-pip python3-wheel
          sudo pip3 install ansible
        working-directory: setup

      - name: "[linux][zsh] install and configure zsh"
        if: matrix.os != 'macos-latest' && matrix.shell == 'zsh'
        run: |
          sudo apt-get install -y --no-install-recommends zsh
          sudo chsh -s /bin/zsh `whoami`

      - name: Set up the test environment.
        run: make setup_ansible_dependencies
        working-directory: setup

      - name: Test the playbook's syntax.
        run: make ansible_lint
        working-directory: setup

      - name: Test the playbook.
        run: make ansible_install
        env:
          ANSIBLE_FORCE_COLOR: '1'
        working-directory: setup

      - name: Check home
        run: |
          ls -la $HOME
          ls -la $HOME/.config
