# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Test Shell installation process when on bash
  integration_shell_bash:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends curl

      - name: Set default shell
        run: sudo chsh -s /bin/bash `whoami`

      - name: Run install script
        run: curl https://raw.githubusercontent.com/PabloScolpino/dotfiles/master/setup/terminal_setup.sh | bash

  # Test Shell installation process when on zsh
  integration_shell_zsh:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends curl zsh

      - name: Set default shell
        run: sudo chsh -s /bin/zsh `whoami`

      - name: Run install script
        run: curl https://raw.githubusercontent.com/PabloScolpino/dotfiles/master/setup/terminal_setup.sh | bash

  # Test ansible installation process
  integration_ansible:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install test dependencies.
        run: |
          sudo apt-get install -y --no-install-recommends python3-setuptools python3-pip python3-wheel
          sudo pip3 install ansible

      - name: Set up the test environment.
        run: ansible-galaxy install -r requirements.yml
        working-directory: setup

      - name: Test the playbook's syntax.
        run: ansible-playbook main.yml --syntax-check
        working-directory: setup

      - name: Test the playbook.
        run: ansible-playbook main.yml -i inventory
        env:
          ANSIBLE_FORCE_COLOR: '1'
