---
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  integration-shell-bash:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends curl

      - name: Set default shell
        run: sudo chsh -s /bin/bash `whoami`

      - name: Run install script
        run: curl https://raw.githubusercontent.com/PabloScolpino/dotfiles/master/setup/terminal_setup.sh | bash

      - name: Check home
        run: |
          ls -la $HOME
          ls -la $HOME/.config

  integration-shell-zsh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends curl zsh

      - name: Set default shell
        run: sudo chsh -s /bin/zsh `whoami`

      - name: Run install script
        run: curl https://raw.githubusercontent.com/PabloScolpino/dotfiles/master/setup/terminal_setup.sh | bash

      - name: Check home
        run: |
          ls -la $HOME
          ls -la $HOME/.config

  integration-ansible-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install test dependencies.
        run: |
          sudo apt-get install -y --no-install-recommends python3-setuptools python3-pip python3-wheel
          sudo pip3 install ansible

      - name: Set up the test environment.
        run: ansible-galaxy install -r requirements.yml
        working-directory: setup

      - name: Test the playbook's syntax.
        run: ansible-playbook main.yml --syntax-check
        working-directory: setup

      - name: Test the playbook.
        run: ansible-playbook main.yml -i inventory
        env:
          ANSIBLE_FORCE_COLOR: '1'
        working-directory: setup

      - name: Check home
        run: |
          ls -la $HOME
          ls -la $HOME/.config

  integration-ansible-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install test dependencies.
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install ansible

      - name: Set up the test environment.
        run: ansible-galaxy install -r requirements.yml
        working-directory: setup

      - name: Test the playbook's syntax.
        run: ansible-playbook main.yml --syntax-check
        working-directory: setup

      - name: Test the playbook.
        run: ansible-playbook main.yml -i inventory
        env:
          ANSIBLE_FORCE_COLOR: '1'
        working-directory: setup

      - name: Check home
        run: |
          ls -la $HOME
          ls -la $HOME/.config
